# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-20 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('no', models.FloatField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('contens', models.CharField(blank=True, max_length=3000, null=True)),
                ('xdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'buser',
                'managed': False,
            },
        ),
    ]
